<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Negar</name>
   <tag></tag>
   <elementGuidId>eee8ec73-0219-483c-91f7-fa4c2782d4e6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[9]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.cf1lHZ.cf2MAH > button.cf2Lf6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>17db8452-5eda-4ded-a99c-8f8ad11dd511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cookiefirst-action</name>
      <type>Main</type>
      <value>reject</value>
      <webElementGuid>95c8d395-8bb8-4d2b-aa2b-343441d0fdf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bca221e8-75e0-44b9-b9e3-a064f2671de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cookiefirst-outline-accent-color</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>36feedce-e837-4d3e-b55b-16b3aa0ca2f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cookiefirst-button</name>
      <type>Main</type>
      <value>secondary</value>
      <webElementGuid>85289806-ce76-4a1a-ba32-93a937c82a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b936bcf1-7ebe-4f27-9640-0e51aebc5087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cf2Lf6</value>
      <webElementGuid>760507c1-274f-40f7-93eb-1aa0ff733f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Negar</value>
      <webElementGuid>8562eff8-ab43-4ec1-97b1-18e8f7d28451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Negar</value>
      <webElementGuid>105e5b75-af5f-4db3-8352-3aa1bd150bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cookiefirst-root&quot;)/div[@class=&quot;cf2CeT notranslate cf2DrG&quot;]/div[@class=&quot;cf3E9g cf2tVG&quot;]/div[@class=&quot;cfAdwL cf7ddU&quot;]/div[@class=&quot;cf2L3T cfysV4 cf2mE1&quot;]/div[@class=&quot;cf3Tgk cf2pAE cf1IKf&quot;]/div[@class=&quot;cf1lHZ cf2MAH&quot;]/button[@class=&quot;cf2Lf6&quot;]</value>
      <webElementGuid>5c294d74-6ec7-44fa-bca2-f3d17f5b267c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[9]</value>
      <webElementGuid>a152bd5d-40c2-41b1-922c-224c94458296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cookiefirst-root']/div/div/div[2]/div[2]/div[2]/div[2]/button</value>
      <webElementGuid>70370323-24e9-4e67-98af-ad701b9e3978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceitar todos'])[1]/following::button[1]</value>
      <webElementGuid>3246648e-c50e-41ff-942c-c6222eb6ffe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nós usamos cookies'])[1]/following::button[2]</value>
      <webElementGuid>ccc01d1d-6b49-4b5e-971a-dadf5c2fbf22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Não, ajustar'])[1]/preceding::button[1]</value>
      <webElementGuid>9e5a3226-787c-4a34-ac3e-5a2cf070b715</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>e3304111-da76-46d1-9b58-3928d5a431ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Negar' or . = 'Negar')]</value>
      <webElementGuid>9cb923fd-a4c3-4860-aa7d-c88606bff563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
