<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Estado</name>
   <tag></tag>
   <elementGuidId>62808f15-be14-4faf-af11-b23ae02d1983</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='states']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#states</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9c93b5f5-c5b5-4b3b-a4e0-e466bda9dff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>states</value>
      <webElementGuid>9a7afbed-ec2b-4837-90d6-3d61db13ba27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>states</value>
      <webElementGuid>0a7801df-2631-4b5e-bf9e-7fb99f00150b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>uw21e21f0</value>
      <webElementGuid>9ac0d90f-d6d3-41a6-8c97-16afe2d7cef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uw-rm-form</name>
      <type>Main</type>
      <value>fx</value>
      <webElementGuid>ab34b4ae-5cef-4d5b-9777-7d475dac79d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EstadoAcreAcreAlagoasAmapáAmazonasBahiaCearáDistrito FederalEspírito SantoGoiásMaranhãoMato GrossoMato Grosso do SulMinas GeraisParanáParaíbaParáPernambucoPiauíRio Grande do NorteRio Grande do SulRio de JaneiroRondôniaRoraimaSanta CatarinaSergipeSão PauloTocantins</value>
      <webElementGuid>3c5f15fe-c293-436b-899e-75264ab421c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;states&quot;)</value>
      <webElementGuid>c0f39f4b-23d6-4d1a-b6f9-d1c3dcaa10e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='states']</value>
      <webElementGuid>8fbaab6d-5a95-4f24-902c-5aff1962e3b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portlet-unimed-mais-proxima']/div/div/select</value>
      <webElementGuid>8bdf23d0-7c2c-40db-ae46-6dc9e449397d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unimed mais próxima'])[4]/following::select[1]</value>
      <webElementGuid>9a8cf1f6-a3f4-46f8-add9-1a8d995cf205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Nacional Unimed'])[1]/preceding::select[2]</value>
      <webElementGuid>a8effc81-0d7a-45ac-adf9-9263faff35b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conheça'])[1]/preceding::select[2]</value>
      <webElementGuid>81f883c9-066e-4131-bba1-50c498942641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>c9236b35-da18-4f83-ab40-2ff15eee9d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'states' and @id = 'states' and (text() = 'EstadoAcreAcreAlagoasAmapáAmazonasBahiaCearáDistrito FederalEspírito SantoGoiásMaranhãoMato GrossoMato Grosso do SulMinas GeraisParanáParaíbaParáPernambucoPiauíRio Grande do NorteRio Grande do SulRio de JaneiroRondôniaRoraimaSanta CatarinaSergipeSão PauloTocantins' or . = 'EstadoAcreAcreAlagoasAmapáAmazonasBahiaCearáDistrito FederalEspírito SantoGoiásMaranhãoMato GrossoMato Grosso do SulMinas GeraisParanáParaíbaParáPernambucoPiauíRio Grande do NorteRio Grande do SulRio de JaneiroRondôniaRoraimaSanta CatarinaSergipeSão PauloTocantins')]</value>
      <webElementGuid>c9486b0f-75e6-4c9d-82ed-41aea010a211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
