<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Selecione a cidade</name>
   <tag></tag>
   <elementGuidId>bb9c9351-09b5-463a-aa30-18d41a90fdc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='citys']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#citys</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f677b5fe-9955-456d-938e-7bc7ae860dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>citys</value>
      <webElementGuid>6143923c-d9f6-450b-90b6-1246a9757517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>citys</value>
      <webElementGuid>56fc28b5-dcfc-44e2-a3ef-d666e681f2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4cfbe74e-110e-4917-ae8a-58441a4c4513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-uw-rm-form</name>
      <type>Main</type>
      <value>fx</value>
      <webElementGuid>49ad9d49-3854-46e6-81d8-c67b4b9a15a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Selecione a cidade</value>
      <webElementGuid>47e5187d-0e7e-4d9a-9402-c90e8acc0783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;citys&quot;)</value>
      <webElementGuid>e0734c5a-d3ef-4df0-9c28-d5643d716192</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='citys']</value>
      <webElementGuid>f36b863e-e1a1-4bc9-9130-8b06c609248f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='portlet-unimed-mais-proxima']/div/div/select[2]</value>
      <webElementGuid>ef36f030-cf61-4a65-b494-434804e857f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unimed mais próxima'])[4]/following::select[2]</value>
      <webElementGuid>30d79bac-f772-47ff-8c6c-94436cbb7e88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Nacional Unimed'])[1]/preceding::select[1]</value>
      <webElementGuid>2841e313-86e1-4404-a20c-a01be4e48189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conheça'])[1]/preceding::select[1]</value>
      <webElementGuid>7adca94f-cd45-4726-baa2-4dc545d526b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
      <webElementGuid>cd92c9c2-cbcb-4a2a-81fe-5298309fd077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'citys' and @id = 'citys' and (text() = 'Selecione a cidade' or . = 'Selecione a cidade')]</value>
      <webElementGuid>f0de3960-fc96-4aa9-80e4-f6ec671780fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
